services:
  db-dev:
    image: mongo:8.0
    hostname: mongo_dev
    env_file:
      - ./mongo.env
    restart: always
    ports:
      - '27017:27017'

  db-seed:
    build: seed/mongo
    env_file:
      - ./mongo.env
    volumes:
      - ./seed:/seed
