services:
  db-dev:
    image: mongo:8.0
    hostname: mongo_dev
    env_file:
      - ./mongo.env
    restart: always
    ports:
      - '27017:27017'

  db-import:
    #build: ./seed/mongo
    image: marcelomjx/projeto-eng-soft-db-import:latest
    volumes:
      - ./seed:/seed
    env_file:
      - ./mongo.env
