services:
  db-dev:
    image: mongo:8.0
    hostname: container_1
    env_file:
      - ./mongo.env
    restart: always
    ports:
      - '27017:27017'

  db-import:
    build: ./datasets
    volumes:
      - ./datasets:/datasets
    env_file:
      - ./mongo.env
